config/routes.rb
Imrollin::Application.routes.draw do
  resources :categories
  resources :images

  match 'create_category/:name/:image_id' => 'categories#create'
  match 'delete_category/:name/:image_id' => 'categories#destroy'
  match 'image_categories/:image_id' => 'categories#index'
  match 'images_category/:name' => 'images#index'
  root :to => 'images#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :images
end

app/models/image.rb
require 'RMagick'

class Image < ActiveRecord::Base
  attr_accessible :filename, :md5, :taken_at

  has_and_belongs_to_many :categories

  before_validation :calculate_hash, :extract_date, :set_created_tag
  after_validation :create_thumbnail

  validates_uniqueness_of :md5

  def url_medium
    '/thumbs/medium/' + md5 + '.' + get_extension
  end

  def url_small
    '/thumbs/small/' + md5 + '.' + get_extension
  end

  def url_original
    filename
  end

  def previous_image
    self.class.first(:conditions => ["id > ?", self.id], :order => "id asc")
  end

  def next_image
    self.class.first(:conditions => ["id < ?", self.id], :order => "id desc")
  end

  def formated_date

    return 'N/A' if taken_at.nil?

    months = ['Janeiro', 'Fevereiro', 'Marco', 'Abril',
              'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro',
              'Outubro', 'Novembro', 'Dezembro']
    day, month, year = taken_at.day, months[taken_at.month], taken_at.year

    "Dia #{day} de #{month} de #{year}."
  end

  private

  def get_extension
    filename.split('.')[-1]
  end

  IMAGES_PATH = './public/images/'
  THUMBS_PATH = './public/thumbs/'

  def is_jpeg? filename
    ['jpeg','jpg','JPG','JPEG'].include? get_extension
  end

  def calculate_hash
    text = IO.read(IMAGES_PATH + filename)
    self.md5 = Digest::MD5.hexdigest(text)
  end

  def extract_date
    # only works for jpeg files for now
    if is_jpeg? filename
        begin
          date = EXIFR::JPEG.new(IMAGES_PATH + filename).date_time
          self.taken_at = date.to_date if date
        rescue
          Rails.logger.error filename
        end
    end
  end

  public
  def create_thumbnail

    # dont create in case of errors
    return if errors.size > 0

    small, medium = File.exists?('./public' + url_small), File.exists?('./public' + url_medium)

    unless medium && small
      begin
        img = Magick::Image.read(IMAGES_PATH + filename).first

        # medium thumb
        unless medium
          Rails.logger.puts 'Resizing medium ' + filename
          img.change_geometry("640x480") do |cols, rows, i|
            i.resize(cols, rows).write './public' + url_medium
          end
        end
        #small thumb
        unless small
          Rails.logger.puts 'Resizing small ' + filename
          img.change_geometry("150x95") do |cols, rows, i|
            i.resize(cols, rows).write './public' + url_small
          end
        end
      rescue Exception => e
        Rails.logger.puts e
      end
    end
  end

  def set_created_tag
     if taken_at
          year = taken_at.year
          c = Category.find_or_create_by_name(year.to_s)
          categories << c
     end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
      Rails.logger.puts params[:image_id].inspect
    if (params[:image_id])
      @categories = Image.find(params[:image_id]).categories
    else
      @categories = Category.all
    end

    # Serve the categories as a json with all their names
    @categories.map! do |c| c.name end

    respond_to do |format|
      format.json { render json: @categories}
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.where(:name => params[:id])[0]
    @images = @category.images

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.find_or_create_by_name params[:name]
    @image = Image.find(params[:image_id])

    if @category.save
      @image.categories << @category
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    # Delete category from an image
    @category = Category.where(:name => params[:name])
    @image = Image.find(params[:image_id])

    @image.categories -= @category

    # If the category has no more images, delete ir
    if @category.first.images.size == 0
      @category.first.delete
    end

    redirect_to @image
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.json
  def index
    page = (params[:page] || 1).to_i
    per_page = 16

    if (params[:name])
      id = Category.where(:name => params[:name])[0].id
      @images = Image.paginate_by_sql(
        ['SELECT "images".* FROM "images" INNER JOIN "categories_images" ON
         "images"."id" = "categories_images"."image_id" WHERE "categories_images"."category_id" = ' + id.to_s],
         :page => page,
         :order => 'id DESC',
         :per_page => per_page
      )
      @category = params[:name]
      count = Category.where(:name => params[:name])[0].images.count
    else
      @images = Image.paginate(:page => params[:page], :per_page => per_page, :order => 'id DESC')
      count = Image.count
    end

    @next = page + 1
    @previous = page - 1

    @next = nil if page*per_page >= count
    @previous = nil if @previous < 1

    respond_to do |format|
      format.html
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    @previous = @image.previous_image
    @next = @image.next_image

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def get_locale_title
        'Organize suas fotos'
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/categories/index.json.erb
{ categories : <%= @categories.map { |c| c.name } %> }

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br />
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :md5 %><br />
    <%= f.text_field :md5 %>
  </div>
  <div class="field">
    <%= f.label :taken_at %><br />
    <%= f.date_select :taken_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<div id="image-section">

  <% if @category %>
  <div id="category-title">
    Mostando imagens de '<%= @category %>'
  </div>
  <% end %>

  <% @images.each do |img| %>

    <%= link_to image_tag(img.url_small, :value => img.id), img,
        :class => 'image-box', :title => img.md5 %>
  <% end %>
</div>

<div id="interface">

    <div id="image-control">
        <%= link_to '<- Anterior', url_for(:page => @previous), :id => 'image-previous' if @previous %>
        <%= link_to 'Próxima ->', url_for(:page => @next), :id => 'image-next' if @next %>
    </div>

</div>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<div id="image-section">
    <%= link_to image_tag(@image.url_medium, :id => 'image-show', :value => @image.id), @image.url_original %>
</div>

<div id="image-data">
    <p>
      <b>Arquivo:</b>
      <%= link_to truncate(@image.url_original, :length => 30), @image.url_original %>
    </p>

    <p>
      <b>Tirada em:</b>
      <%= @image.formated_date %>
    </p>
</div>

</br>
<strong> Esta foto pertence às seguintes categorias: </strong>

<div id="image-categories">
</div>

<div id="interface">

    <div id="image-control">
        <%= link_to '<- Anterior', @previous, :id => 'image-previous' if @previous %>
        <%= link_to 'Próxima ->', @next, :id => 'image-next' if @next %>
    </div>

    <div id="add-category">
        <strong>Nova categoria:</strong>
            <input id="new-category" type="text">
            <a href="#"> Adicione! </a>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> IMRollin - <%= get_locale_title %> </title>
  <%= stylesheet_link_tag "style" %>
  <%= javascript_include_tag "jquery.min" %>
  <%= javascript_include_tag "interface.js" %>

  <%= csrf_meta_tags %>
</head>

<body>
    <div id="wrap">
        <div id="mainbody">

            <div id="content">

            <div id="leftsidebar">
                <div id="categories">
                    <h2>Categorias</h2>
                    <div id="all-categories">
                    </div>
                </div>

                <div id="show-all">
                <h3><a href="/">Todas fotos</a></h3>
                </div>
            </div>

            <%= yield %>

            </div>
        </div>
    </div>
</body>
</html>